/* 
 * Copyright 2017 Albert Santos.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* global Leeboard, LBPhysics, LBGeometry, LBMath, LBFoils, LBSailSim */

// Need to tie together Phaser and our Vessel stuff.
// What is the tie-in?
// Need to take the forces from Vessel and apply them to the Phaser physics object.
// Need to take the position/rotation of the phaser object and apply it to the
// Vessel.
// Why do we need P2? Because of collision detection.

/**
 * A basic instance of a foil, a foil is something that generates a force due
 * to its interaction with a flowing fluid.
 * @constructor
 * @param {object} foil The {@link LBFoils.Foil} object that generates the forces.
 * @param {object} obj3D    The 3D object that defines the local coordinate system
 * of the foil.
 * @param {number} mass The mass of the foil.
 * @param {object} centerOfMass The center of mass of the foil.
 */
LBSailSim.FoilInstance = function(foil, obj3D, mass, centerOfMass) {
    LBPhysics.RigidBody.call(this, obj3D, mass, centerOfMass);
    this.foil = foil || new LBFoils.Foil();
    this.workingPos = LBGeometry.createVector3();
};

LBSailSim.FoilInstance.prototype = Object.create(LBPhysics.RigidBody.prototype);
LBSailSim.FoilInstance.prototype.constructor = LBSailSim.FoilInstance;

LBSailSim.FoilInstance.prototype.updateFoilForce = function(dt, flow) {
    this.workingPos.copy(0, 0, this.foil.sliceZ);
    this.workingPos.applyMatrix4(this.coords.worldXfrm);
    
    this.workingQInf = LBSailSim.getFlowVelocity(flow, this.workingPos, this.workingQInf);
    this.workingResultant = this.foil.calcWorldForce(flow.density, this.workingQInf,
            this.coords);
    this.addWorldResultant(this.workingResultant);
};

/**
 * Loads the foil instance's properties from properties in a data object.
 * @param {object} data The data to load from.
 * @param {object} sailEnv  The sailing environment, passed to {@link LBFoils.Foil} for
 * loading the {@link LBFoils.ClCdCurve} object.
 * @returns {object}    this.
 */
LBSailSim.FoilInstance.prototype.load = function(data, sailEnv) {
    LBPhysics.RigidBody.prototype.load.call(this, data);
    if (Leeboard.isVar(data.foil)) {
        this.foil = LBFoils.Foil.createFromData(data.foil, sailEnv);
    }
    return this;
};



/**
 * An instance of a propulsor, which is an object that exerts some type of propulsive
 * force.
 * @constructor
 * @param {object} obj3D    The object 3D defining the local coordinate system of
 * the propulsor.
 * @param {number} maxForce The maximum force magnitude generated by the propulsor, if
 * not defined it is set to {Number.MAX_VALUE}.
 * @returns {LBSailSim.Propulsor}
 */
LBSailSim.Propulsor = function(obj3D, maxForce) {
    LBPhysics.RigidBody.call(this, obj3D, 0);
    this.forceMag = 0;
    this.forceDir = LBGeometry.createVector3(1, 0, 0);
    this.maxForce = maxForce || Number.MAX_VALUE;
    
    this.workingForce = LBGeometry.createVector3();
    this.workingPos = LBGeometry.createVector3();
};

LBSailSim.Propulsor.prototype = Object.create(LBPhysics.RigidBody.prototype);
LBSailSim.Propulsor.prototype.constructor = LBSailSim.Propulsor;

LBSailSim.Propulsor.prototype.updateForce = function(dt) {
    var forceMag = LBMath.clamp(this.forceMag, 0, this.maxForce);
    if (forceMag === 0) {
        return this;
    }
    
    this.workingForce.copy(this.forceDir);
    this.workingForce.multiplyScalar(forceMag);
    this.workingForce.applyMatrix4Rotation(this.coords.worldXfrm);
    
    this.workingPos.zero();
    this.workingPos.applyMatrix4(this.coords.worldXfrm);
    
    this.addWorldForce(this.workingForce, this.workingPos);
            
    return this;
};


//
// For controls:
// Need:
// LBControls.xxxController, which defines the limits.
// Maybe add XYController
// 
// Controllee:
// For vessels have:
//      AngleControllee:
//          Orientation axis? Or just x,y,z and angle.
//          Controls an Object3D.rotation
//
//      TranslationControllee:
//          A line defines the position of the 3D object, could be a parametric curve.
//          Controls an Object3D.position
//
//      ValueControllee:
//          Throttle.
//

/**
 * Container representing a vessel that floats. Vessels support:
 * <li>Aerofoils, which are {@link LBSailSim.FoilInstance} based objects that are driven by the atmosphere.
 * <li>Hydrofoils,which are {@link LBSailSim.FoilInstance} based objects that are driven by the water.
 * <li>Propulsors, which are {@link LBSailSim.Propulsor} based objects.
 * TODO: Add ballast, which is just a LBPhysics.RigidBody.
 * @constructor
 * @param {object} sailEnv  The sailing environment.
 * @param {type} obj3D
 * @returns {LBSailSim.Vessel}
 */
LBSailSim.Vessel = function(sailEnv, obj3D) {
    LBPhysics.RigidBody.call(this, obj3D);

    this.sailEnv = sailEnv;
    this.hydroFoils = [];
    this.aeroFoils = [];
    this.propulsors = [];
    this.ballasts = [];
    
    this.controllers = [];
    
    // Later:
    //this.crew = [];

};

LBSailSim.Vessel.prototype = Object.create(LBPhysics.RigidBody.prototype);
LBSailSim.Vessel.prototype.constructor = LBSailSim.Vessel;

LBSailSim.Vessel.prototype.addAeroFoil = function(foilInstance) {
    this.aeroFoils.push(foilInstance);
    this.addPart(foilInstance);
    return this;
};

LBSailSim.Vessel.prototype.addHydroFoil = function(foilInstance) {
    this.hydroFoils.push(foilInstance);
    this.addPart(foilInstance);
    return this;
};

LBSailSim.Vessel.prototype.addPropulsor = function(propulsor) {
    this.propulsors.push(propulsor);
    this.addPart(propulsor);
    return this;
};

LBSailSim.Vessel.prototype.addBallast = function(ballast) {
    this.ballasts.push(ballast);
    this.addPart(ballast);
    return this;
};

LBSailSim.Vessel.prototype.addController = function(controller, controllee) {
    controller.controllee = controllee;
    this.controllers.push(controller);
    return this;
};

LBSailSim.Vessel.prototype.removeParts = function(foils) {
    for (var i = 0; i < foils.length; ++i) {
        this.removePart(foils[i]);
    }
    foils.splice(0, foils.length);
    return foils;
};

LBSailSim.Vessel.prototype.createFoilInstanceForLoad = function(data) {
    // We're not using {@link LBPhysics.RigidBody#createFromData() because we need to pass
    // sailEnv to {@link LBFoils.Foil#load()}.
    if (Leeboard.isVar(data.construct)) {
        return eval(data.construct);
    }
    
    return new FoilInstance();
};

LBSailSim.Vessel.prototype.loadFoilInstance = function(data) {    
    var foilInstance = this.createFoilInstanceForLoad(data);
    if (Leeboard.isVar(foilInstance)) {
        foilInstance.load(data, this.sailEnv);
    }    
    return foilInstance;
};

LBSailSim.Vessel.prototype.loadFoils = function(data, foils) {
    if (!Leeboard.isVar(data)) {
        return this;
    }
    
    for (var i = 0; i < data.length; ++i) {
        var foilData = data[i];
        var foilInstance = this.loadFoilInstance(foilData);
        if (Leeboard.isVar(foilInstance)) {
            foils.push(foilInstance);
            this.addPart(foilInstance);
        }
    }
    return this;
};

LBSailSim.Vessel.prototype.loadPropulsors = function(data) {
    if (!Leeboard.isVar(data)) {
        return this;
    }
    return this;
};

LBSailSim.Vessel.prototype.createBallastForLoad = function(data) {
    return LBPhysics.RigidBody.createFromData(data);
};

LBSailSim.Vessel.prototype.loadBallasts = function(data) {
    if (!Leeboard.isVar(data)) {
        return this;
    }
    
    for (var i = 0; i < data.length; ++i) {
        var ballast = this.createBallastForLoad(data[i]);
        if (ballast !== undefined) {
            this.addBallast(ballast);
        }
    }
    return this;
};

LBSailSim.Vessel.prototype.load = function(data) {
    // Clear out the existing settings...
    this.aeroFoils = this.removeParts(this.aeroFoils);
    this.hydroFoils = this.removeParts(this.hydroFoils);
    this.propulsors = this.removeParts(this.propulsors);
    this.ballasts = this.removeParts(this.ballasts);
    
    LBPhysics.RigidBody.prototype.load.call(this, data);
    this.typeName = data.typeName;
    this.instances = data.instances;
    
    this.loadFoils(data.aeroFoils, this.aeroFoils);
    this.loadFoils(data.hydroFoils, this.hydroFoils);
    this.loadPropulsors(data.propulsors);
    this.loadBallasts(data.ballasts);
    
    return this;
};

LBSailSim.Vessel.prototype.updateFoilForces = function(dt, flow, foils) {
    for (var i = 0; i < foils.length; ++i) {
        foils[i].updateFoilForce(dt, flow);
    }
    return this;
};

LBSailSim.Vessel.prototype.updateForces = function(dt) {
    this.clearForces();
    
    this.updateCoords(dt);
    
    this.updateFoilForces(dt, this.sailEnv.wind, this.aeroFoils);
    this.updateFoilForces(dt, this.sailEnv.water, this.hydroFoils);
    
    for (var i = 0; i < this.propulsors.length; ++i) {
        this.propulsors[i].updateForce(dt);
    }
    
    // Need the hull resistance...
    
    // Need to add gravity.
    
    return this;
};


/**
 * Creates a vessel object based upon properties in a data object.
 * @param {object} data
 * @param {object} sailEnv
 * @returns {object}    The created vessel, {undefined} if data is not defined.
 */
LBSailSim.Vessel.createFromData = function(data, sailEnv) {
    if (!Leeboard.isVar(data)) {
        return undefined;
    }
    
    var vessel;
    if (Leeboard.isVar(data.construct)) {
        vessel = eval(data.construct);
        vessel.sailEnv = sailEnv;
    }
    else {
        vessel = new LBSailSim.Vessel(sailEnv);
    }
    
    return vessel.load(data);
};
